### ISSUE TITLE
Truncate (regular files)

### ISSUE THREAD

**Issue by yuheho7749** [yuheho7749/uwufs#29]

**Comment by PigBrainOverflow** [comment]
I'm working on remove_dblk_no_from_inode() (including indirect blocks), which may support your truncate().

**Comment by yuheho7749** [comment]
That could be used for small truncates, but I also have __free_{single,double,triple}_indirect_blk helper functions to remove larger chunks on my development branch.

**Comment by PigBrainOverflow** [comment]
Sure. Great! I planned to write a large range remove (like remove all dblks after a start_index), but seems you will use several more fine controlled helpers, so I will postpone writing that. (Tell me if you really need it).
